### ISSUE TITLE
Bug with Eris JS in Fengari

### ISSUE THREAD

**Issue by UrNightmaree** [fengari-lua/fengari#205]
Hello, so I make a Discord Bot with Eris using Fengari-Interop. When I use event `messageCreate` and then get the message content, it return `nil`.

Here's the code
```lua
local js = require 'js'
local g = js.global
local new = js.new

local env = require 'env'
env:config(); local process = g.process

local eris = require 'eris'

local intents = new(g.Object)
intents.intents = new(g.Array,'guildMessages')

local bot = new(eris,process.env.TOKEN,intents)
local sendMsg = function(channel,content)
  bot:sendMessage(channel,content)
end

bot:on('ready',function()
  print 'ready'
end)

bot:on('messageCreate',function(msg)
  print(msg.content)
end)

bot:connect()
```

**Comment by RyanSquared** [comment]
Can you clarify the `nil` you get? If it's *just* nil, and it's not an attempt to index nil error, that means there could be other fields in the table. It may be useful to iterate through the table like so:

```lua
for k, v in pairs(msg)
    print(k, v)
end
```

**Comment by UrNightmaree** [comment]
here's the output
```
╭─lua4life@localhost ~/fengari/eris
╰─$ node .
ready
_eventsnode:events:505
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot convert object to primitive value
    at String.concat (<anonymous>)
    at __tostring (/home/lua4life/fengari/eris/node_modules/fengari-interop/src/js.js:777:11)
    at luaD_precall (/home/lua4life/fengari/eris/node_modules/fengari/src/ldo.js:169:21)
    at luaD_call (/home/lua4life/fengari/eris/node_modules/fengari/src/ldo.js:366:10)
    at Object.luaD_callnoyield (/home/lua4life/fengari/eris/node_modules/fengari/src/ldo.js:685:5)
    at lua_callk (/home/lua4life/fengari/eris/node_modules/fengari/src/lapi.js:968:13)
    at lua_call (/home/lua4life/fengari/eris/node_modules/fengari/src/lapi.js:976:5)
    at luaL_callmeta (/home/lua4life/fengari/eris/node_modules/fengari/src/lauxlib.js:571:5)
    at luaL_tolstring (/home/lua4life/fengari/eris/node_modules/fengari/src/lauxlib.js:588:9)
    at luaB_tostring (/home/lua4life/fengari/eris/node_modules/fengari/src/lbaselib.js:141:5)
Emitted 'error' event on Client instance at:
    at Shard.emit (/home/lua4life/fengari/eris/node_modules/eris/lib/gateway/Shard.js:245:26)
    at Shard._onWSMessage (/home/lua4life/fengari/eris/node_modules/eris/lib/gateway/Shard.js:2460:18)
    at WebSocket.emit (node:events:527:28)
    at Receiver.receiverOnMessage (/home/lua4life/fengari/eris/node_modules/ws/lib/websocket.js:1178:20)
    at Receiver.emit (node:events:527:28)
    at Receiver.dataMessage (/home/lua4life/fengari/eris/node_modules/ws/lib/receiver.js:528:14)
    at Receiver.getData (/home/lua4life/fengari/eris/node_modules/ws/lib/receiver.js:446:17)
    at Receiver.startLoop (/home/lua4life/fengari/eris/node_modules/ws/lib/receiver.js:148:22)
    at Receiver._write (/home/lua4life/fengari/eris/node_modules/ws/lib/receiver.js:83:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
```

**Comment by UrNightmaree** [comment]
I replace `pairs` with `js.of`. Like above, throw error.

```
╭─lua4life@localhost ~/fengari/eris
╰─$ node .
ready
node:events:518
    throw err; // Unhandled 'error' event
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ("/home/lua4life/fengari/eris/main.lua:23: bad argument #1 to 'of' (object not iterable)")
    at new NodeError (node:internal/errors:372:5)
    at Client.emit (node:events:516:17)
    at Shard.emit (/home/lua4life/fengari/eris/node_modules/eris/lib/gateway/Shard.js:245:26)
    at Shard._onWSMessage (/home/lua4life/fengari/eris/node_modules/eris/lib/gateway/Shard.js:2460:18)
    at WebSocket.emit (node:events:527:28)
    at Receiver.receiverOnMessage (/home/lua4life/fengari/eris/node_modules/ws/lib/websocket.js:1178:20)
    at Receiver.emit (node:events:527:28)
    at Receiver.dataMessage (/home/lua4life/fengari/eris/node_modules/ws/lib/receiver.js:528:14)
    at Receiver.getData (/home/lua4life/fengari/eris/node_modules/ws/lib/receiver.js:446:17)
    at Receiver.startLoop (/home/lua4life/fengari/eris/node_modules/ws/lib/receiver.js:148:22) {
  code: 'ERR_UNHANDLED_ERROR',
  context: "/home/lua4life/fengari/eris/main.lua:23: bad argument #1 to 'of' (object not iterable)"
}
```

**Comment by UrNightmaree** [comment]
I check if `msg` is actually an `object`, and it does.
```
╭─lua4life@localhost ~/fengari/eris
╰─$ node .
ready
object
```

**Comment by Mehgugs** [comment]
Try using ```lua
bot:on('messageCreate',function(_, msg)
  print(msg.content)
end)
```

**Comment by UrNightmaree** [comment]
Its working, thanks for the help @Mehgugs 😄

```
╭─lua4life@localhost ~/fengari/eris
╰─$ node .
ready
test
```

**Comment by Mehgugs** [comment]
For those wondering, the first argument in this scenario is what would normally be the implicit `this` object in a js call, I believe that is due to how node emitters bind their callbacks.
